// taglines.js
const taglines = [
  "digital solutions for the right price",
  "ashes to ashes",
  "I'm not owned! I'm not owned!",
  "...but we don't want the Irish!",
  "error: failed to load MIDI background music",
  "Old age and treachery will beat youth and skill any day",
  "everything's computer",
  "we do not negotiate with terrorists",
  "optimized for 56k modems",
  "these colors don't run (how do I remove eggplant stains?)",
  "[your ad here]",
  "hah! gayyyyy!",
  "there is no way that you are from my loins",
  "serious inquiries only",
  "certified Odoo partner",
  "srs bsns fr",
  "one love",
  "duck tales! ah woo-ooh!",
  "guitar riffs, flames, confetti, and thou",
  "Kilroy was here",
  "you seem awfully cavalier. a lot like your brother.",
  "WHY DID YOU REDEEM",
  "Call me Dr. Ew",
  "Durian, Ruby, Eggplant, Wenge",
  "twelve and six, in a plain wrapper",
  "pining for the fjords",
  "Terwilliger bunts one",
  "i hope Tom is ok",
  "you're never only just a hat",
  "has anyone really been far even as decided to use even go want to do look more like?",
  "smokin' and jokin' like you're back on the block",
  "stompin' turts",
  "AYBABTU: the first, the finest",
  "'smy burfday",
  "the lesser of two weevils"
];
